[package]
name = "logik"
version = "3.0.2"
authors = ["Thomas Queiroz <thomasqueirozb@gmail.com>"]
edition = "2018"

[dependencies]
clap = { version = "3.2.20", features = ["derive"] }
color-eyre = "0.6"
thiserror = "1.0"
